name = "backend"
compatibility_date = "2024-08-03"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzliZDQwMmUtZDg1OS00YmIyLTg4NTMtYzhhOTc3ZjE1NGIxIiwidGVuYW50X2lkIjoiYTA4NjU3YjEzZDY1MzQwMWEwZmU3YzdmNGJiZjk1M2Y2MzQ3ZDJmNWViNDE1ODliZDIzOWE3M2NkMGFiMTkxOCIsImludGVybmFsX3NlY3JldCI6IjVlZDdlMTI0LTRhYjMtNGU2NS1hZDNkLTQzOTIxMmNkOWVkNiJ9.UBjTKYVBJyTvZwh3V3a1jymmof1WJxwGFjFqEVG9LEM"
JWT_SECRET='shshshs'
